from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Optional, List
from .models import User, Lead, Chef, Offer, Booking, ConversationMessage

class Repo(ABC):
    @abstractmethod
    def upsert_user(self, u: User) -> User: ...
    @abstractmethod
    def get_user_by_external(self, channel: str, external_id: str) -> Optional[User]: ...

    @abstractmethod
    def create_lead(self, lead: Lead) -> Lead: ...
    @abstractmethod
    def get_active_lead(self, user_id: str) -> Optional[Lead]: ...
    @abstractmethod
    def update_lead(self, lead: Lead) -> Lead: ...

    @abstractmethod
    def list_chefs(self) -> List[Chef]: ...
    @abstractmethod
    def get_chef(self, chef_id: str) -> Optional[Chef]: ...

    @abstractmethod
    def create_offer(self, offer: Offer) -> Offer: ...
    @abstractmethod
    def list_offers(self, lead_id: str) -> List[Offer]: ...

    @abstractmethod
    def create_booking(self, booking: Booking) -> Booking: ...
    @abstractmethod
    def get_booking(self, booking_id: str) -> Optional[Booking]: ...
    @abstractmethod
    def update_booking(self, booking: Booking) -> Booking: ...

    @abstractmethod
    def add_message(self, msg: ConversationMessage) -> ConversationMessage: ...
    @abstractmethod
    def list_messages(self, user_id: str, limit: int = 50) -> List[ConversationMessage]: ...
